sudo: required

language: python

services:
  - docker

env:
  COMPOSE_VERSION: 1.9.0

addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts:
      - www.itstime4science.ru

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 
script:
  - make build
