version: "2"

services:
  loadb_dev:
    build: loadb_dev
    ports:
      - "${DEV_IP}:80:80"
    depends_on:
      - "web_dev"
    networks:
      - dev.itstime4science.ru
  web_dev:
    build: web
    volumes:
      - ./web:/code
    networks:
      - dev.itstime4science.ru

networks:
  dev.itstime4science.ru:
    
