version: "2"

services:
  loadb_dev:
    build: loadb_dev
    ports:
      - "${DEV_IP}:80:80"
    depends_on:
      - "web_dev1"
    networks:
      - dev.itstime4science.ru
  web_dev1:
    build: web
    volumes:
      - ./web:/code
    environment:
      - DEV=1
      - MYSQL_DATABASE_HOST=${MYSQL_DATABASE_HOST}
      - MYSQL_DATABASE_PORT=${MYSQL_DATABASE_PORT}
      - MYSQL_DATABASE_USER=${MYSQL_DATABASE_USER}
      - MYSQL_DATABASE_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      - MYSQL_DATABASE_DB=${MYSQL_DATABASE_DB}
    networks:
      - dev.itstime4science.ru
networks:
  dev.itstime4science.ru:
    
