version: "2"

services:
  loadb:
    build: loadb
    ports:
      - "${PROD_IP}:80:80"
    depends_on:
      - "web"
    networks:
      - itstime4science.ru
  web:
    build: web
    volumes:
      - ./web:/code
    networks:
      - itstime4science.ru
networks:
  itstime4science.ru:
