version: "2"

services:
  loadb_dev:
    build: loadb_dev
    ports:
      - "${DEV_IP}:80:80"
    depends_on:
      - "web_dev1"
      - "web_dev2"
    networks:
      - dev.itstime4science.ru
  web_dev1:
    build: web
    volumes:
      - ./web:/code
    environment:
      - DEV=1
    networks:
      - dev.itstime4science.ru
  web_dev2:
    build: web
    volumes:
      - ./web:/code
    environment:
      - DEV=1
    networks:
      - dev.itstime4science.ru
networks:
  dev.itstime4science.ru:
    
